# docker-compose configuration file for CodiMD + Postgres + WOPI bridge
#
# Build with:   docker-compose -f codimd.yaml build
# Run with:     DBPWD='yourdbpassword' HOST='http://yourserver' docker-compose -f codimd.yaml up -d
#

version: "3"
services:
  database:
    image: postgres:11.6-alpine
    container_name: codimd-postgres
    hostname: cbox-codimd-postgres
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=${DBPWD}
      - POSTGRES_DB=codimd
    network_mode: codinet
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  frontend:
    image: hackmdio/hackmd:cern
    container_name: codimd-web
    hostname: cbox-codimd-web
    environment:
      - CMD_DB_URL=postgres://codimd:${DBPWD}@codimd-postgres/codimd
      - CMD_AUTO_VERSION_CHECK=false
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_ALLOW_ANONYMOUS_VIEWS=true
      - CMD_SAVE_HOOK=http://codimd-wopi.codinet:8000
    depends_on:
      - database
    ports:
      - 3000:3000
    network_mode: codinet
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always
  wopibridge:
    build:
      context: .
      dockerfile: wopibridge-poc.Dockerfile
    image: wopibridge-poc:cern
    container_name: codimd-wopi
    hostname: cbox-codimd-wopi
    environment:
      - CODIMD_INT_URL=http://codimd-web.codinet:3000
      - CODIMD_EXT_URL=${HOST}:3000
      - WOPIBRIDGE_URL=${HOST}:8000
      - CODIMD_STORAGE_PATH=/mnt/codimd_storage
    depends_on:
      - frontend
    network_mode: codinet
    restart: always
    ports:
      - 8000:8000
    volumes:
      - upload-data:/mnt/codimd_storage
    healthcheck:
      test: ["CMD", "curl", "--insecure", "http://localhost:8000"]
      interval: 600s
      timeout: 5s
      retries: 3

volumes:
  database-data: {}
  upload-data: {}

networks:
  codinet:
