# docker-compose configuration file for CodiMD + Postgres + WOPI bridge
#
# Build with:   docker-compose -f codimd.yaml build
# Run with:     WOPIHOST=https://wopi.cernbox.cern.ch CODIHOST='https://yourcodimd' docker-compose -f codimd.yaml up -d
#

version: "3.1"
services:
  wopibridge:
    build:
      context: .
      dockerfile: wopibridge-poc.Dockerfile
    image: wopibridge-poc:cern
    container_name: codimd-wopi
    hostname: cbox-codimd-wopi
    environment:
      - CODIMD_EXT_URL=${CODIHOST}:3000
      - WOPIBRIDGE_URL=${WOPIHOST}:8000
    ports:
      - 8000:8000
    secrets:
      - cert.pem
      - key.pem
    restart: always
    healthcheck:
      test: ["CMD", "curl", "https://localhost:8000"]
      interval: 600s
      timeout: 5s
      retries: 3

secrets:
  cert.pem:
    file: /etc/grid-security/cernbox-hostcert.pem
  key.pem:
    file: /etc/grid-security/cernbox-hostkey.pem
  dhparam.pem:
    file: ./dhparams.pem
