# docker-compose configuration file for WopiServer
#
# Run with: docker-compose --project-name wopiserver -f wopiserver.yaml up -d
#

version: "3.3"
services:
  wopiserver:
    build:
      context: .
      dockerfile: wopiserver${WOPI_DOCKER_TYPE}.Dockerfile
    image: wopiserver:cern
    container_name: wopiserver
    hostname: cbox-iop-wopiserver
    network_mode: "bridge"
    restart: always
    ports:
      - 8880:8880
    volumes:
      - config:/etc/wopi
      - storage:/var/wopi_local_storage
      - logs:/var/log/wopi
    healthcheck:
      test: ["CMD", "curl", "--insecure", "http://localhost:8880"]
      interval: 300s
      timeout: 5s
      retries: 3
      #start_period: 60s

volumes:
  config:
  storage:
  logs:
