# docker-compose configuration file for WOPI server + WOPI bridge
#
# Build with:   docker-compose -f wopi.yaml build
# Run with:     WOPIHOST='https://wopi.cernbox.cern.ch' CODIHOST='https://cbox-codimd-01' docker-compose -f wopi.yaml up -d
#

version: "3.1"
services:
  wopibridge:
    image: cs3org/wopibridge:latest
    container_name: wopibridge
    hostname: cbox-wopibridge
    environment:
      - CODIMD_EXT_URL=${CODIHOST}:3000
      - WOPIBRIDGE_URL=${WOPIHOST}:8000
    ports:
      - 8000:8000
    secrets:
      - cert.pem
      - key.pem
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--insecure", "https://localhost:8000"]
      interval: 600s
      timeout: 5s
      retries: 3

secrets:
  cert.pem:
    file: /etc/grid-security/cernbox-hostcert.pem
  key.pem:
    file: /etc/grid-security/cernbox-hostkey.pem

