# docker-compose configuration file for WopiForCodiMD
#
# Build with:   docker-compose -f wopicodimd.yaml build
# Run with:     docker-compose --project-name wopicodimd -f wopicodimd.yaml up -d
#
#
version: "3.3"
services:
  wopicodimd:
    build:
      context: .
      dockerfile: wopicodimd.Dockerfile
    image: wopicodimd:cern
    container_name: wopicodimd
    hostname: cbox-codimd-wopi
    network_mode: "bridge"
    restart: always
    ports:
      - 8000:8000
    volumes:
      - wopicodimd_config:/etc/wopi
      - wopicodimd_logs:/var/log/wopi
    healthcheck:
      test: ["CMD", "curl", "--insecure", "http://localhost:8000"]
      interval: 600s
      timeout: 5s
      retries: 3

volumes:
  wopicodimd_logs:
  wopicodimd_config:
