# docker-compose configuration file for Collabora
#
# Build with:   docker-compose -f collabora.yaml build
# Run with:     docker-compose --project-name collabora -f collabora.yaml up -d
#
#
version: "2.3"
services:
  collabora:
    build:
     context: .
     dockerfile: collabora.Dockerfile
    image: collabora:cern
    container_name: collabora
    network_mode: "bridge"
    stdin_open: true
    tty: true
    restart: always
    cap_add:
      - MKNOD
    ports:
      - 10443:9980
    environment:
      domain: "cernboxwebpreview.cern.ch"
      server_name: "cbox-wopi-01.cern.ch:9980"
      username: "dummy_admin"
      passowrd: "4RhPT2J0KX"
      DONT_GEN_SSL_CERT: "True"
    healthcheck:
      test: ["CMD", "curl", "--insecure", "https://localhost:9980"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s

