# docker-compose configuration file
version: "2"
services:

  # OnlyOffice Document Server
  onlyoffice:
    build:
     context: .
     dockerfile: onlyoffice-poc.Dockerfile
    image: onlyoffice-poc:cern
    container_name: onlyoffice-poc
    hostname: onlyoffice-poc
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 8000:80
      - 4443:443
    volumes:
      - onlyofficedata:/var/www/onlyoffice/Data
      - onlyofficelogs:/var/log/onlyoffice

volumes:
  onlyofficedata:
  onlyofficelogs:

