# docker-compose configuration file for WopiServer
#
# Build with:   docker-compose -f wopiserver.yaml build
# Run with:     docker-compose --project-name wopiserver -f wopiserver.yaml up -d
#
#
version: "3.3"
services:
  wopiserver:
    build:
      context: .
      dockerfile: wopiserver.Dockerfile
    image: wopiserver:cern
    container_name: wopiserver
    hostname: cbox-wopi-docker-01
    network_mode: "bridge"
    restart: always
    ports:
      - 8443:8443
    volumes:
      - logs:/var/log/wopi
    healthcheck:
      test: ["CMD", "curl", "--insecure", "https://localhost:8443"]
      interval: 60s
      timeout: 5s
      retries: 3
      #start_period: 60s

volumes:
  logs:
