name: Releases
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
        - tag: wopiserver:${{ github.ref_name }}
          file: wopiserver.Dockerfile
        - tag: wopiserver:${{ github.ref_name }}-xrootd
          file: wopiserver-xrootd.Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ${{ matrix.tag }}
        uses: docker/build-push-action@v3
        env:
          VERSION: ${{ github.ref_name }}
        with:
          context: .
          push: true
          file: ${{ matrix.file }}
          tags: ${{ format('{0}/{1}', vars.DOCKERHUB_ORGANIZATION, matrix.tag) }}
