name: Releases
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        include:
        - file: wopiserver.Dockerfile
          tags: ${{ vars.DOCKERHUB_ORGANIZATION }}/wopiserver:${{ github.ref_name }},${{ vars.DOCKERHUB_ORGANIZATION }}/wopiserver:latest
          platform: linux/amd64
          image: python:3.11-alpine
        - file: wopiserver.Dockerfile
          tags: ${{ vars.DOCKERHUB_ORGANIZATION }}/wopiserver:${{ github.ref_name }},${{ vars.DOCKERHUB_ORGANIZATION }}/wopiserver:latest
          platform: linux/arm64
          image: python:3.10-slim-buster
        - file: wopiserver-xrootd.Dockerfile
          tags: ${{ vars.DOCKERHUB_ORGANIZATION }}/wopiserver:${{ github.ref_name }}-xrootd
          platform: linux/amd64
    uses: cs3org/reva/.github/workflows/docker.yml@master
    secrets: inherit
    with:
      file: ${{ matrix.file }}
      tags: ${{ matrix.tags }}
      build-args: VERSION=${{ github.ref_name }},BASEIMAGE=${{ matrix.image }}
      push: ${{ github.event_name != 'workflow_dispatch' }}
      platforms: ${{ matrix.platform }}
