name: Releases
on:
  push:
    tags:
      - "*"

jobs:
  release:
    strategy:
      matrix:
        include:
        - tags: ${{ vars.DOCKERHUB_ORGANIZATION }}/wopiserver:${{ github.ref_name }},${{ vars.DOCKERHUB_ORGANIZATION }}/wopiserver:latest
          file: wopiserver.Dockerfile
        - tags: ${{ vars.DOCKERHUB_ORGANIZATION }}/wopiserver:${{ github.ref_name }}-xrootd
          file: wopiserver-xrootd.Dockerfile
    uses: cs3org/reva/.github/workflows/docker.yml@master
    secrets: inherit
    with:
      file: ${{ matrix.file }}
      tags: ${{ matrix.tags }}
      build-args: VERSION=${{ github.ref_name }}
      push: true
